spring:
  security:
    oauth2:
      client:
        registration:
          twitter:
            client-id: ${TWITTER_CLIENT_ID}
            client-secret: ${TWITTER_CLIENT_SECRET}
  jackson:
    default-property-inclusion: NON_NULL

logging:
  level:
    org.springframework: DEBUG