name: Build twitter-reactive-labs

on:
  push:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    name: Build Project using Java ${{ matrix.java }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Get Github Info
        run: |
          REPOSITORY_PARTS=($(echo $GITHUB_REPOSITORY | tr "/" "\n"))
          echo "::set-env name=GITHUB_OWNER::${REPOSITORY_PARTS[0]}"
          echo "::set-env name=GITHUB_PROJECT::${REPOSITORY_PARTS[1]}"
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/${GITHUB_OWNER}/packages" }]'
          servers: '[{ "id": "github", "username": "${GITHUB_OWNER}", "password" : "${PACKAGES_TOKEN}" }]'

      - name: Remove Snapshot
        run: mvn versions:set -DremoveSnapshot

      - name: Build
        run: mvn clean install

      - name: Publish to GitHub Packages
        run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/rj93/packages

      - name: Set Next Snapshot Version
        run: mvn versions:set -DnextSnapshot

      - name: Commit Next Snapshot Version
        uses: EndBug/add-and-commit@v4
        with:
          message: "Increment Snapshot Version"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}